apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fohjkjz0v-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/fohjkjz0v-java-quarkus-gitops